// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqamvpmplsdbacdskhfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xYW12cG1wbHNkYmFjZHNraGZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUwNDgxMTEsImV4cCI6MjA1MDYyNDExMX0.qsGxB95sDIQcWzKABJIpkHH_Y6NJlDxqxQPNJhfhc58";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);